extends:
  - airbnb-base
  - airbnb-typescript/base
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
  - simple-import-sort
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
